# Generated by Django 3.0.7 on 2020-06-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField()),
                ('shorten_url', models.CharField(max_length=200, unique=True)),
                ('hits', models.IntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='users.User')),
            ],
        ),
    ]
